# Generated by Django 5.2.1 on 2025-05-13 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('biography', models.TextField(blank=True, null=True)),
                ('photo_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Authors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookauthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'BookAuthor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookcopies',
            fields=[
                ('copy_id', models.AutoField(primary_key=True, serialize=False)),
                ('format', models.TextField()),
                ('is_borrowed', models.IntegerField(blank=True, null=True)),
                ('in_inventory', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'BookCopies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookgenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'BookGenre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('isbn', models.TextField(unique=True)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('cover_image_url', models.TextField(blank=True, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('added_date', models.TextField()),
                ('is_deleted', models.IntegerField()),
                ('deleted_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Borrowings',
            fields=[
                ('borrowing_id', models.AutoField(primary_key=True, serialize=False)),
                ('format', models.TextField()),
                ('borrow_date', models.TextField()),
                ('return_date', models.TextField(blank=True, null=True)),
                ('current_renew_count', models.IntegerField(blank=True, null=True)),
                ('last_renewal_date', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Borrowings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('role', models.IntegerField()),
                ('is_a_member', models.IntegerField()),
                ('membership_last_renewed', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField()),
                ('last_login', models.TextField(blank=True, null=True)),
                ('profile_image_url', models.TextField(blank=True, null=True)),
                ('last_seen', models.TextField(blank=True, null=True)),
                ('is_subbed_to_newsletter', models.IntegerField(blank=True, null=True)),
                ('theme_preference', models.TextField(blank=True, null=True)),
                ('is_deleted', models.IntegerField()),
                ('deleted_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('favorite_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.TextField()),
            ],
            options={
                'db_table': 'Favorites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Friendships',
            fields=[
                ('friendship_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.TextField()),
                ('created_at', models.TextField()),
            ],
            options={
                'db_table': 'Friendships',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Genres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Globalparameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'GlobalParameters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Membershiptypes',
            fields=[
                ('membership_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('borrow_duration_in_days', models.IntegerField()),
                ('same_book_borrow_count_limit', models.IntegerField()),
                ('max_renewal_count', models.IntegerField()),
                ('renewal_duration_in_days', models.IntegerField()),
                ('overdue_fee_in_dollars', models.FloatField()),
            ],
            options={
                'db_table': 'MembershipTypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificationcategories',
            fields=[
                ('notification_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'NotificationCategories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('timestamp', models.TextField()),
                ('is_read', models.IntegerField()),
            ],
            options={
                'db_table': 'Notifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'Publisher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('timestamp', models.TextField()),
            ],
            options={
                'db_table': 'Ratings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='frontend.users')),
                ('password_hash', models.BinaryField()),
            ],
            options={
                'db_table': 'Credentials',
                'managed': False,
            },
        ),
    ]
