# Generated by Django 5.2.1 on 2025-05-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_books_audiobook_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='profile_picture_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
