# Generated by Django 5.2.1 on 2025-05-17 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_admin_profile_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowings',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.books'),
        ),
    ]
