# Generated by Django 5.2.1 on 2025-05-17 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_borrowings_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowings',
            name='book',
        ),
    ]
